#-----------------------------------------------------------------
# Azure Kubernetes - ADD integration  
#  
#-----------------------------------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: aks-admin-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"] # ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: aks-admin-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-admin-rolebinding-roleref
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  # Azure AD Group "az-ad_grp_admin"
  name: "f0ef04e6-294a-4159-b563-04a8a8c66134" #"REPLACE-WITH-YOUR-AAD-GROUP-OBJECT-ID"